#ifndef CONFIG_FEATURES_H_
#define CONFIG_FEATURES_H_

#cmakedefine BLADE_DATA_DIR "@BLADE_DATA_DIR@"

#cmakedefine BLADE_PLUGIN_DIR "@BLADE_PLUGIN_DIR@"
#cmakedefine BLADE_FULL_PLUGIN_DIR "@BLADE_FULL_PLUGIN_DIR@"

#cmakedefine BLADE_INSTALL_PREFIX "@BLADE_INSTALL_PREFIX@"

#endif
